include:
  - local: '.gitlab/templates.yml'

stages:
  - check
  - build
  - test
  - deploy

workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_REF_PROTECTED == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

variables:
  OSEC_NSPECT_ID: NSPECT-SI4K-XVXQ
  OSEC_SONARQUBE_ENABLED: true
  OSEC_OMNI_SANITIZER_ENABLED: true
  OSEC_CHECKMARX_ENABLED: false
  OSEC_OMNI_PULSE_ENABLED: false

check_code_format:
  extends: [.default_job]
  stage: check
  script:
    - uv lock --check
    - uv run --group dev poe lint

.build_base:
  extends: [.default_job]
  stage: build
  needs: [] # do not wait for checks
  script:
    - uv run --group dev poe update-readme
    - uv build
    - git restore README.md
  artifacts:
    paths:
      - dist/

build_linux:
  extends: [.build_base]

build_windows:
  extends: [.build_base, .setup_windows]

.test_base:
  extends: [.default_job]
  stage: test
  script:
    - uv run --group dev poe test-ci
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: .coverage.xml
      junit: .results.xml
    paths:
      - .coverage.xml
      - .results.xml
    expire_in: 1 week

test_linux:
  extends: [.test_base]
  needs: ["build_linux"]

test_windows:
  extends: [.test_base, .setup_windows]
  needs: ["build_windows"]

test_wheel_linux:
  extends: [.default_job]
  stage: test
  needs: ["build_linux"]
  script:
    # Create a fresh virtual environment to test the wheel using uv
    - uv venv /tmp/wheel_test_env
    - source /tmp/wheel_test_env/bin/activate

    # Install the wheel directly using uv
    - uv pip install --index-strategy unsafe-best-match dist/*.whl

    # Test conversion
    - mkdir -p /tmp/test_outputs
    - urdf_usd_converter -h

test_wheel_windows:
  extends: [.default_job, .setup_windows]
  stage: test
  needs: ["build_windows"]
  script:
    # Create a fresh virtual environment to test the wheel using uv
    - uv venv wheel_test_env
    - wheel_test_env\Scripts\activate.ps1

    # Find and install the wheel file
    - $wheelFile = Get-ChildItem -Path "dist" -Filter "*.whl" | Select-Object -First 1
    - uv pip install --index-strategy unsafe-best-match $wheelFile.FullName

    # Test conversion
    - New-Item -ItemType Directory -Force -Path test_outputs
    - urdf_usd_converter -h

.deploy_base:
  extends: [.deploy_job]
  stage: deploy
  script:
    - uv run python ./tools/upload_wheel.py

deploy_tagged:
  extends: [.deploy_base]
  rules:
    - if: $CI_COMMIT_TAG

deploy_preview:
  extends: [.deploy_base]
  when: manual
  rules:
    - if: '$CI_COMMIT_TAG == null && $CI_COMMIT_REF_PROTECTED == "true"'
